input {
  file {
    path => "/data/test_dataset.csv"
    start_position => "beginning"
    sincedb_path => "/dev/null"
  }
}

filter {
  csv {
    separator => ","
    columns => ["timestamp","src_ip","dst_ip","protocol","src_port","dst_port","bytes","duration_ms","label"]
  }
  date {
    match => ["timestamp", "yyyy-MM-dd HH:mm:ss"]
  }
}

output {
  kafka {
    bootstrap_servers => "kafka:9092"
    topic_id => "test-topic"
  }
  stdout { codec => rubydebug }
}

